### PR TITLE
Dockerized Mozilla India Website

### LINKED ISSUE #141: [Feature] Dockerize Mozilla India website
## Feature/Enhancement
 We need to dockerize Mozilla website. Helps in deploying it to the cloud or even an easy process for developers to serve the static site instantly using docker-compose.

**Would you like to work on the issue?**
Yes for sure!

### PR DESCRIPTION
**Pull request by kmehant**
### Fixes #141

**Changes**: 
I have dockerized Mozilla India Website and it resulted in very lightweight **ngnix:alpine** based container. We can easily deploy to the cloud and even have the static site served instantly with a single command using docker-compose. I have made necessary documentation changes too. I believe it's a good option to developers.

### CODE REVIEW

**Comment by kmehant** [comment]
@obitodarky Please review!

**Comment by kmehant** [comment]
@obitodarky @asdofindia Please review!

**Comment by asdofindia** [comment]
Thanks. Hope you will maintain the dockerfile as well. I don't see myself using docker for running an http-server at this moment.

**Comment by kmehant** [comment]
> Thanks. Hope you will maintain the dockerfile as well. I don't see myself using docker for running an http-server at this moment.

Surely !

**Pull request merged**
