### PR TITLE
Updated Regional Groups

### PR DESCRIPTION
**Pull request by thetronjohnson**
**Changes**: 
Added Mozilla Rajasthan to the list of Regional Groups

### CODE REVIEW

**Comment by obitodarky** [comment]
@thetronjohnson can you please share a screenshot of the page?

**Comment by thetronjohnson** [comment]
Screenshot from 2019-07-03 13-36-07

@obitodarky

**Comment by obitodarky** [comment]
Thanks

**Comment by asdofindia** [comment]
Merged this as b62cef63e9956c98260771e7a9134a33d568a935

Thanks for bringing to up the fact that we don't have an enforced code style guide. Have tried to fix that with a4857d2e7227376e948171f01fa6f53d7609d893

**Pull request closed without merging**
