### PR TITLE
Update functionalgroups.json

### PR DESCRIPTION
**Pull request by Lablnet**
https://github.com/MozillaIndia/mozillaindia.github.io/issues/161

### CODE REVIEW

**Comment by asdofindia** [comment]
I believe the graphql queries will also need to be updated as they are case sensitive (probably). Also please ask @harshil1712 if this issue need to be preserved for hacktoberfest.

**Comment by asdofindia** [comment]
Thanks a lot for the contribution, by the way! I was just startled by the speed with which the PR came in.

**Comment by harshil1712** [comment]
Hey @Lablnet thank you for your contribution! :smile: 
It's amazing to see a PR in such a short time! :tada: 
Just curious to know if you're doing this as a part of Hacktoberfest? 
Also the test fail. Can you please make the changes suggested by @asdofindia. That's the reason of why the tests failed.

**Comment by obitodarky** [comment]
@Lablnet thanks a lot for the contribution, but can you please follow the PR template?

**Pull request closed without merging**
