### PR TITLE
Improve data structure for campusclubs.json

### LINKED ISSUE #160: Improve data structure in campusclubs.json file
## Enhancement

**Actual Behaviour**

The campusclubs.json file doesn't follow a proper structure. Different objects contain different fields. 

**Expected Behaviour**

Create a proper data structure for camousclubs.json file. 

**Screenshots of the issue**

**Would you like to work on the issue?**

This is issue open for anyone who is interested in contributing!

### PR DESCRIPTION
**Pull request by achudinovskyh**
Fixes #160 

**Changes**: 
Improved data structure for campusclubs.josn
Now it contains all necessary keys, and you can add any new information, it will be displayed on the page.

### CODE REVIEW

**Comment by asdofindia** [comment]
Thanks for the contribution. 

I think the structure you propose is the same as the old one (the graphql query remains the same, as you can see). And I don't see how that helps. 

Do you think there is an alternative structure where the graphql query need not be changed when a new kind of link is added?

**Comment by achudinovskyh** [comment]
@asdofindia I got your point. I've changed data structure and query, and now you can just add a new link to the array and it will be rendered.

**Comment by asdofindia** [comment]
Looks better now. I would prefer capitalization of first letter in the links, but I think that can be done later. @harshil1712, what do you say?

**Comment by asdofindia** [comment]
Shall merge this after manually making a few changes.

**Comment by asdofindia** [comment]
Thanks. Have cherry-picked a commit.

**Pull request closed without merging**
