### PR TITLE
Changed GitHub to github in the data files

### PR DESCRIPTION
**Pull request by anihm136**
Fixes #[161] 

**Changes**: 

Changed "GitHub" to "github" in data files

### CODE REVIEW

**Comment by obitodarky** [comment]
@anihm136 Please make sure builds pass.

**Comment by anihm136** [comment]
@obitodarky The builds appear to fail because the key values that I changed are being referenced unsuccessfully. However, I am not able to find any file in the repo which uses those key values. How do I go about this?

**Comment by asdofindia** [comment]
The way I would do it is use a tool like `awk` or `ag` to find all occurrences of the keyword in the entire project.

**Comment by In4No** [comment]
> @obitodarky The builds appear to fail because the key values that I changed are being referenced unsuccessfully. However, I am not able to find any file in the repo which uses those key values. How do I go about this?

I am having the same issue when I added logos for the groups. Adding a new field in the json file breaks schema generation. I am getting this error .
There was an error in your GraphQL query:

- Unknown field 'logo' on type 'RegionalgroupsJson!'.

**Comment by anihm136** [comment]
Made some changes to the files referencing those keys. All checks passed now. @asdofindia Thanks for your help!

**Comment by obitodarky** [comment]
> > @obitodarky The builds appear to fail because the key values that I changed are being referenced unsuccessfully. However, I am not able to find any file in the repo which uses those key values. How do I go about this?
> 
> I am having the same issue when I added logos for the groups. Adding a new field in the json file breaks schema generation. I am getting this error .
> There was an error in your GraphQL query:
> 
>     * Unknown field 'logo' on type 'RegionalgroupsJson!'.
>       @asdofindia Any idea whats wrong?

Hi, can you tell us in which file are you getting this error?

**Comment by In4No** [comment]
> > > @obitodarky The builds appear to fail because the key values that I changed are being referenced unsuccessfully. However, I am not able to find any file in the repo which uses those key values. How do I go about this?
> > 
> > 
> > I am having the same issue when I added logos for the groups. Adding a new field in the json file breaks schema generation. I am getting this error .
> > There was an error in your GraphQL query:
> > ```
> > * Unknown field 'logo' on type 'RegionalgroupsJson!'.
> >   @asdofindia Any idea whats wrong?
> > ```
> 
> Hi, can you tell us in which file are you getting this error?

Hey... it got fixed just now. I had to rm -rf .cache manually.

**Comment by asdofindia** [comment]
Trusting @harshil1712's call. I didn't review the code. Thanks everyone.

**Pull request merged**
